baseURL = 'https://ilscev.github.io/bc-gallery/'
languageCode = 'de-de'
title = 'BC Gallerie'
theme = "KeepIt"
[params.share]
Twitter = false
Facebook = false
#Reddit = false
Linkedin = false
#Pinterest = false
#HackerNews = false
#Mix = false
#Tumblr = false
#VKontakte = false
#Douban = false
#Weibo = false